[project]
authors = ["James Bacon <james.bacon@seh.ox.ac.uk>", "William Clarke <william.clarke@ndcn.ox.ac.uk>"]
channels = ["conda-forge", "https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/"]
name = "GIRF_PE_Python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.2.4,<3"
matplotlib = ">=3.10.1,<4"
scipy = ">=1.15.2,<2"
fsl_mrs = ">=2.4.3,<3"

[pypi-dependencies]
pypulseq = ">=1.4.2.post1, <2"
twixtools = ">=0.23, <0.24"
